import ProofWidgets.Compat
import ProofWidgets.Component.Basic
import ProofWidgets.Component.FilterDetails
import ProofWidgets.Component.HtmlDisplay
import ProofWidgets.Component.InteractiveSvg
import ProofWidgets.Component.MakeEditLink
import ProofWidgets.Component.OfRpcMethod
import ProofWidgets.Component.Panel.Basic
import ProofWidgets.Component.Panel.GoalTypePanel
import ProofWidgets.Component.Panel.SelectionPanel
import ProofWidgets.Component.PenroseDiagram
import ProofWidgets.Component.Recharts
import ProofWidgets.Data.Html
import ProofWidgets.Data.Svg
import ProofWidgets.Presentation.Expr
